version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
      docker: 18
  pre_build:
    commands:
    - echo "prometheus prebuild step"
    - $(aws ecr get-login --no-include-email --region ${REGION})
    - pip install awscli --upgrade --user
  build:
    commands:
    - echo "pragg build step asdf"
    - docker --version
    - make
    - docker images
    - docker tag weaveworks/prom-aggregation-gateway:latest ${REPOSITORY_URL}/${REPOSITORY_NAME}:${TARGET_IMAGE_NAME}
    - docker push ${REPOSITORY_URL}/${REPOSITORY_NAME}:${TARGET_IMAGE_NAME}
    # make ECS updating manual for now, out of scope
    # current issue: "message": "(service dev-prometheus-ecs-Service-UKCRAFTZ5G1K) was unable to place a task because no container instance met all of its requirements. 
    # Reason: No Container Instances were found in your cluster. For more information, see the Troubleshooting section of the Amazon ECS Developer Guide."
    # - aws ecs update-service --cluster ${CLUSTER_NAME} --region ${REGION} --service ${ECS_SERVICE} --force-new-deployment --desired-count 1
